// Code generated by hertz generator.

package purchase

import (
	"context"

	purchase "buycar/biz/model/purchase"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PurchaseConsult .
// @router /api/consult/purchase [GET]
func PurchaseConsult(ctx context.Context, c *app.RequestContext) {
	var err error
	var req purchase.PurchaseConsultReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(purchase.PurchaseConsultResp)

	c.JSON(consts.StatusOK, resp)
}

// QueryConsult .
// @router /api/consult/query [GET]
func QueryConsult(ctx context.Context, c *app.RequestContext) {
	var err error
	var req purchase.QueryConsultReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(purchase.QueryConsultResp)

	c.JSON(consts.StatusOK, resp)
}
