// Code generated by hertz generator.

package purchase

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _consultMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _purchaseconsultMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryconsultMw() []app.HandlerFunc {
	// your code...
	return nil
}
