// Code generated by hertz generator.

package admin

import (
	"context"

	admin "buycar/biz/model/admin"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// QueryAllConsults .
// @router /api/admin/consult/query [GET]
func QueryAllConsults(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.QueryAllConsultsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.QueryAllConsultsResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminAddUser .
// @router /api/admin/user/add [POST]
func AdminAddUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminAddUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminAddUserResp)

	c.JSON(consts.StatusOK, resp)
}

// AdminDeleteUser .
// @router /api/admin/user/delete [DELETE]
func AdminDeleteUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminDeleteUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.AdminDeleteUserResp)

	c.JSON(consts.StatusOK, resp)
}

// QueryFeedbackAnalysis .
// @router /api/admin/feedback/query [GET]
func QueryFeedbackAnalysis(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.QueryFeedbackAnalysisReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(admin.QueryFeedbackAnalysisResp)

	c.JSON(consts.StatusOK, resp)
}
