// Code generated by hertz generator.

package score

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _scoreMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserscoreMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _giftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _purchasegiftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querygiftlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
