// Code generated by hertz generator.

package score

import (
	"context"

	score "buycar/biz/model/score"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetUserScore .
// @router /api/score [GET]
func GetUserScore(ctx context.Context, c *app.RequestContext) {
	var err error
	var req score.GetUserScoreReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(score.GetUserScoreResp)

	c.JSON(consts.StatusOK, resp)
}

// PurchaseGift .
// @router /api/score/gift/purchase [POST]
func PurchaseGift(ctx context.Context, c *app.RequestContext) {
	var err error
	var req score.PurchaseGiftReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(score.PurchaseGiftResp)

	c.JSON(consts.StatusOK, resp)
}

// QueryGiftList .
// @router /api/score/gift/query [GET]
func QueryGiftList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req score.QueryGiftListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(score.QueryGiftListResp)

	c.JSON(consts.StatusOK, resp)
}
