// Code generated by hertz generator.

package admin

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _consultMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryallconsultsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryfeedbackanalysisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminadduserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _admindeleteuserMw() []app.HandlerFunc {
	// your code...
	return nil
}
