// Code generated by hertz generator.

package user

import (
	"context"

	user "buycar/biz/model/user"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Login .
// @router /api/user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.LoginResp)

	c.JSON(consts.StatusOK, resp)
}

// Register .
// @router /api/user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.RegisterResp)

	c.JSON(consts.StatusOK, resp)
}

// Feedback .
// @router /api/user/feedback [POST]
func Feedback(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.FeedbackReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.FeedbackResp)

	c.JSON(consts.StatusOK, resp)
}
