// Code generated by hertz generator.

package user

import (
	"buycar/biz/middleware"
	"buycar/biz/pack"
	"buycar/biz/service"
	"buycar/pkg/errno"
	"context"

	user "buycar/biz/model/user"

	"github.com/cloudwego/hertz/pkg/app"
)

// Login .
// @router /api/user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.LoginResp)
	date, err := service.NewUserService(ctx, c).LoginIn(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	middleware.AccessTokenJwtMiddleware.LoginHandler(ctx, c)
	middleware.RefreshTokenJwtMiddleware.LoginHandler(ctx, c)

	c.Header("Access-Token", c.GetString("Access-Token"))
	c.Header("Refresh-Token", c.GetString("Refresh-Token"))

	resp.BaseResponse = pack.BuildBaseResp(errno.Success)
	resp.User = date

	pack.SendResponse(c, resp)
}

// Register .
// @router /api/user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.RegisterResp)
	err = service.NewUserService(ctx, c).Register(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.BaseResponse = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}

// Feedback .
// @router /api/user/feedback [POST]
func Feedback(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.FeedbackReq
	err = c.BindAndValidate(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp := new(user.FeedbackResp)
	err = service.NewUserService(ctx, c).CreateFeedback(&req)
	if err != nil {
		pack.BuildFailResponse(c, err)
		return
	}

	resp.BaseResponse = pack.BuildBaseResp(errno.Success)

	pack.SendResponse(c, resp)
}
