// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package purchase

import (
	"buycar/biz/model/module"
	"context"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
)

// 购车咨询请求
type PurchaseConsultReq struct {
	BudgetRange     *string `thrift:"budget_range,1,optional" form:"budget_range" json:"budget_range,omitempty" query:"budget_range"`
	PreferredType   *string `thrift:"preferred_type,2,optional" form:"preferred_type" json:"preferred_type,omitempty" query:"preferred_type"`
	UseCase         *string `thrift:"use_case,3,optional" form:"use_case" json:"use_case,omitempty" query:"use_case"`
	FuelType        *string `thrift:"fuel_type,4,optional" form:"fuel_type" json:"fuel_type,omitempty" query:"fuel_type"`
	BrandPreference *string `thrift:"brand_preference,5,optional" form:"brand_preference" json:"brand_preference,omitempty" query:"brand_preference"`
}

func NewPurchaseConsultReq() *PurchaseConsultReq {
	return &PurchaseConsultReq{}
}

func (p *PurchaseConsultReq) InitDefault() {
}

var PurchaseConsultReq_BudgetRange_DEFAULT string

func (p *PurchaseConsultReq) GetBudgetRange() (v string) {
	if !p.IsSetBudgetRange() {
		return PurchaseConsultReq_BudgetRange_DEFAULT
	}
	return *p.BudgetRange
}

var PurchaseConsultReq_PreferredType_DEFAULT string

func (p *PurchaseConsultReq) GetPreferredType() (v string) {
	if !p.IsSetPreferredType() {
		return PurchaseConsultReq_PreferredType_DEFAULT
	}
	return *p.PreferredType
}

var PurchaseConsultReq_UseCase_DEFAULT string

func (p *PurchaseConsultReq) GetUseCase() (v string) {
	if !p.IsSetUseCase() {
		return PurchaseConsultReq_UseCase_DEFAULT
	}
	return *p.UseCase
}

var PurchaseConsultReq_FuelType_DEFAULT string

func (p *PurchaseConsultReq) GetFuelType() (v string) {
	if !p.IsSetFuelType() {
		return PurchaseConsultReq_FuelType_DEFAULT
	}
	return *p.FuelType
}

var PurchaseConsultReq_BrandPreference_DEFAULT string

func (p *PurchaseConsultReq) GetBrandPreference() (v string) {
	if !p.IsSetBrandPreference() {
		return PurchaseConsultReq_BrandPreference_DEFAULT
	}
	return *p.BrandPreference
}

var fieldIDToName_PurchaseConsultReq = map[int16]string{
	1: "budget_range",
	2: "preferred_type",
	3: "use_case",
	4: "fuel_type",
	5: "brand_preference",
}

func (p *PurchaseConsultReq) IsSetBudgetRange() bool {
	return p.BudgetRange != nil
}

func (p *PurchaseConsultReq) IsSetPreferredType() bool {
	return p.PreferredType != nil
}

func (p *PurchaseConsultReq) IsSetUseCase() bool {
	return p.UseCase != nil
}

func (p *PurchaseConsultReq) IsSetFuelType() bool {
	return p.FuelType != nil
}

func (p *PurchaseConsultReq) IsSetBrandPreference() bool {
	return p.BrandPreference != nil
}

func (p *PurchaseConsultReq) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_PurchaseConsultReq[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *PurchaseConsultReq) ReadField1(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.BudgetRange = _field
	return nil
}
func (p *PurchaseConsultReq) ReadField2(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.PreferredType = _field
	return nil
}
func (p *PurchaseConsultReq) ReadField3(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.UseCase = _field
	return nil
}
func (p *PurchaseConsultReq) ReadField4(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.FuelType = _field
	return nil
}
func (p *PurchaseConsultReq) ReadField5(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.BrandPreference = _field
	return nil
}

func (p *PurchaseConsultReq) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("PurchaseConsultReq"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *PurchaseConsultReq) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetBudgetRange() {
		if err = oprot.WriteFieldBegin("budget_range", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.BudgetRange); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *PurchaseConsultReq) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetPreferredType() {
		if err = oprot.WriteFieldBegin("preferred_type", thrift.STRING, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.PreferredType); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *PurchaseConsultReq) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetUseCase() {
		if err = oprot.WriteFieldBegin("use_case", thrift.STRING, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.UseCase); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *PurchaseConsultReq) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetFuelType() {
		if err = oprot.WriteFieldBegin("fuel_type", thrift.STRING, 4); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.FuelType); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *PurchaseConsultReq) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetBrandPreference() {
		if err = oprot.WriteFieldBegin("brand_preference", thrift.STRING, 5); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.BrandPreference); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *PurchaseConsultReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PurchaseConsultReq(%+v)", *p)

}

type PurchaseConsultResp struct {
	BaseResponse *module.BaseResp `thrift:"baseResponse,1,required" form:"baseResponse,required" json:"baseResponse,required" query:"baseResponse,required"`
	Consult      *module.Consult  `thrift:"consult,2,optional" form:"consult" json:"consult,omitempty" query:"consult"`
}

func NewPurchaseConsultResp() *PurchaseConsultResp {
	return &PurchaseConsultResp{}
}

func (p *PurchaseConsultResp) InitDefault() {
}

var PurchaseConsultResp_BaseResponse_DEFAULT *module.BaseResp

func (p *PurchaseConsultResp) GetBaseResponse() (v *module.BaseResp) {
	if !p.IsSetBaseResponse() {
		return PurchaseConsultResp_BaseResponse_DEFAULT
	}
	return p.BaseResponse
}

var PurchaseConsultResp_Consult_DEFAULT *module.Consult

func (p *PurchaseConsultResp) GetConsult() (v *module.Consult) {
	if !p.IsSetConsult() {
		return PurchaseConsultResp_Consult_DEFAULT
	}
	return p.Consult
}

var fieldIDToName_PurchaseConsultResp = map[int16]string{
	1: "baseResponse",
	2: "consult",
}

func (p *PurchaseConsultResp) IsSetBaseResponse() bool {
	return p.BaseResponse != nil
}

func (p *PurchaseConsultResp) IsSetConsult() bool {
	return p.Consult != nil
}

func (p *PurchaseConsultResp) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetBaseResponse bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetBaseResponse = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetBaseResponse {
		fieldId = 1
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_PurchaseConsultResp[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_PurchaseConsultResp[fieldId]))
}

func (p *PurchaseConsultResp) ReadField1(iprot thrift.TProtocol) error {
	_field := module.NewBaseResp()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.BaseResponse = _field
	return nil
}
func (p *PurchaseConsultResp) ReadField2(iprot thrift.TProtocol) error {
	_field := module.NewConsult()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Consult = _field
	return nil
}

func (p *PurchaseConsultResp) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("PurchaseConsultResp"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *PurchaseConsultResp) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("baseResponse", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.BaseResponse.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *PurchaseConsultResp) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetConsult() {
		if err = oprot.WriteFieldBegin("consult", thrift.STRUCT, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Consult.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *PurchaseConsultResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PurchaseConsultResp(%+v)", *p)

}

// 查询咨询记录请求
type QueryConsultReq struct {
	ConsultID *string `thrift:"consult_id,1,optional" form:"consult_id" json:"consult_id,omitempty" query:"consult_id"`
}

func NewQueryConsultReq() *QueryConsultReq {
	return &QueryConsultReq{}
}

func (p *QueryConsultReq) InitDefault() {
}

var QueryConsultReq_ConsultID_DEFAULT string

func (p *QueryConsultReq) GetConsultID() (v string) {
	if !p.IsSetConsultID() {
		return QueryConsultReq_ConsultID_DEFAULT
	}
	return *p.ConsultID
}

var fieldIDToName_QueryConsultReq = map[int16]string{
	1: "consult_id",
}

func (p *QueryConsultReq) IsSetConsultID() bool {
	return p.ConsultID != nil
}

func (p *QueryConsultReq) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_QueryConsultReq[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *QueryConsultReq) ReadField1(iprot thrift.TProtocol) error {

	var _field *string
	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		_field = &v
	}
	p.ConsultID = _field
	return nil
}

func (p *QueryConsultReq) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("QueryConsultReq"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *QueryConsultReq) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetConsultID() {
		if err = oprot.WriteFieldBegin("consult_id", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.ConsultID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *QueryConsultReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryConsultReq(%+v)", *p)

}

type QueryConsultResp struct {
	BaseResponse *module.BaseResp `thrift:"baseResponse,1,required" form:"baseResponse,required" json:"baseResponse,required" query:"baseResponse,required"`
	Consult      *module.Consult  `thrift:"consult,2,optional" form:"consult" json:"consult,omitempty" query:"consult"`
}

func NewQueryConsultResp() *QueryConsultResp {
	return &QueryConsultResp{}
}

func (p *QueryConsultResp) InitDefault() {
}

var QueryConsultResp_BaseResponse_DEFAULT *module.BaseResp

func (p *QueryConsultResp) GetBaseResponse() (v *module.BaseResp) {
	if !p.IsSetBaseResponse() {
		return QueryConsultResp_BaseResponse_DEFAULT
	}
	return p.BaseResponse
}

var QueryConsultResp_Consult_DEFAULT *module.Consult

func (p *QueryConsultResp) GetConsult() (v *module.Consult) {
	if !p.IsSetConsult() {
		return QueryConsultResp_Consult_DEFAULT
	}
	return p.Consult
}

var fieldIDToName_QueryConsultResp = map[int16]string{
	1: "baseResponse",
	2: "consult",
}

func (p *QueryConsultResp) IsSetBaseResponse() bool {
	return p.BaseResponse != nil
}

func (p *QueryConsultResp) IsSetConsult() bool {
	return p.Consult != nil
}

func (p *QueryConsultResp) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16
	var issetBaseResponse bool = false

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
				issetBaseResponse = true
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	if !issetBaseResponse {
		fieldId = 1
		goto RequiredFieldNotSetError
	}
	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_QueryConsultResp[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
RequiredFieldNotSetError:
	return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("required field %s is not set", fieldIDToName_QueryConsultResp[fieldId]))
}

func (p *QueryConsultResp) ReadField1(iprot thrift.TProtocol) error {
	_field := module.NewBaseResp()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.BaseResponse = _field
	return nil
}
func (p *QueryConsultResp) ReadField2(iprot thrift.TProtocol) error {
	_field := module.NewConsult()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Consult = _field
	return nil
}

func (p *QueryConsultResp) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("QueryConsultResp"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *QueryConsultResp) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("baseResponse", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.BaseResponse.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *QueryConsultResp) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetConsult() {
		if err = oprot.WriteFieldBegin("consult", thrift.STRUCT, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Consult.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *QueryConsultResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryConsultResp(%+v)", *p)

}

type ConsultService interface {
	PurchaseConsult(ctx context.Context, req *PurchaseConsultReq) (r *PurchaseConsultResp, err error)

	QueryConsult(ctx context.Context, req *QueryConsultReq) (r *QueryConsultResp, err error)
}

type ConsultServiceClient struct {
	c thrift.TClient
}

func NewConsultServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *ConsultServiceClient {
	return &ConsultServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewConsultServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *ConsultServiceClient {
	return &ConsultServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewConsultServiceClient(c thrift.TClient) *ConsultServiceClient {
	return &ConsultServiceClient{
		c: c,
	}
}

func (p *ConsultServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *ConsultServiceClient) PurchaseConsult(ctx context.Context, req *PurchaseConsultReq) (r *PurchaseConsultResp, err error) {
	var _args ConsultServicePurchaseConsultArgs
	_args.Req = req
	var _result ConsultServicePurchaseConsultResult
	if err = p.Client_().Call(ctx, "purchaseConsult", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
func (p *ConsultServiceClient) QueryConsult(ctx context.Context, req *QueryConsultReq) (r *QueryConsultResp, err error) {
	var _args ConsultServiceQueryConsultArgs
	_args.Req = req
	var _result ConsultServiceQueryConsultResult
	if err = p.Client_().Call(ctx, "queryConsult", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

type ConsultServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      ConsultService
}

func (p *ConsultServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *ConsultServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *ConsultServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewConsultServiceProcessor(handler ConsultService) *ConsultServiceProcessor {
	self := &ConsultServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self.AddToProcessorMap("purchaseConsult", &consultServiceProcessorPurchaseConsult{handler: handler})
	self.AddToProcessorMap("queryConsult", &consultServiceProcessorQueryConsult{handler: handler})
	return self
}
func (p *ConsultServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}

type consultServiceProcessorPurchaseConsult struct {
	handler ConsultService
}

func (p *consultServiceProcessorPurchaseConsult) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := ConsultServicePurchaseConsultArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("purchaseConsult", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := ConsultServicePurchaseConsultResult{}
	var retval *PurchaseConsultResp
	if retval, err2 = p.handler.PurchaseConsult(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing purchaseConsult: "+err2.Error())
		oprot.WriteMessageBegin("purchaseConsult", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("purchaseConsult", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type consultServiceProcessorQueryConsult struct {
	handler ConsultService
}

func (p *consultServiceProcessorQueryConsult) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := ConsultServiceQueryConsultArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("queryConsult", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := ConsultServiceQueryConsultResult{}
	var retval *QueryConsultResp
	if retval, err2 = p.handler.QueryConsult(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing queryConsult: "+err2.Error())
		oprot.WriteMessageBegin("queryConsult", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("queryConsult", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type ConsultServicePurchaseConsultArgs struct {
	Req *PurchaseConsultReq `thrift:"req,1"`
}

func NewConsultServicePurchaseConsultArgs() *ConsultServicePurchaseConsultArgs {
	return &ConsultServicePurchaseConsultArgs{}
}

func (p *ConsultServicePurchaseConsultArgs) InitDefault() {
}

var ConsultServicePurchaseConsultArgs_Req_DEFAULT *PurchaseConsultReq

func (p *ConsultServicePurchaseConsultArgs) GetReq() (v *PurchaseConsultReq) {
	if !p.IsSetReq() {
		return ConsultServicePurchaseConsultArgs_Req_DEFAULT
	}
	return p.Req
}

var fieldIDToName_ConsultServicePurchaseConsultArgs = map[int16]string{
	1: "req",
}

func (p *ConsultServicePurchaseConsultArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConsultServicePurchaseConsultArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ConsultServicePurchaseConsultArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ConsultServicePurchaseConsultArgs) ReadField1(iprot thrift.TProtocol) error {
	_field := NewPurchaseConsultReq()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Req = _field
	return nil
}

func (p *ConsultServicePurchaseConsultArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("purchaseConsult_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ConsultServicePurchaseConsultArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *ConsultServicePurchaseConsultArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConsultServicePurchaseConsultArgs(%+v)", *p)

}

type ConsultServicePurchaseConsultResult struct {
	Success *PurchaseConsultResp `thrift:"success,0,optional"`
}

func NewConsultServicePurchaseConsultResult() *ConsultServicePurchaseConsultResult {
	return &ConsultServicePurchaseConsultResult{}
}

func (p *ConsultServicePurchaseConsultResult) InitDefault() {
}

var ConsultServicePurchaseConsultResult_Success_DEFAULT *PurchaseConsultResp

func (p *ConsultServicePurchaseConsultResult) GetSuccess() (v *PurchaseConsultResp) {
	if !p.IsSetSuccess() {
		return ConsultServicePurchaseConsultResult_Success_DEFAULT
	}
	return p.Success
}

var fieldIDToName_ConsultServicePurchaseConsultResult = map[int16]string{
	0: "success",
}

func (p *ConsultServicePurchaseConsultResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConsultServicePurchaseConsultResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ConsultServicePurchaseConsultResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ConsultServicePurchaseConsultResult) ReadField0(iprot thrift.TProtocol) error {
	_field := NewPurchaseConsultResp()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Success = _field
	return nil
}

func (p *ConsultServicePurchaseConsultResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("purchaseConsult_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ConsultServicePurchaseConsultResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *ConsultServicePurchaseConsultResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConsultServicePurchaseConsultResult(%+v)", *p)

}

type ConsultServiceQueryConsultArgs struct {
	Req *QueryConsultReq `thrift:"req,1"`
}

func NewConsultServiceQueryConsultArgs() *ConsultServiceQueryConsultArgs {
	return &ConsultServiceQueryConsultArgs{}
}

func (p *ConsultServiceQueryConsultArgs) InitDefault() {
}

var ConsultServiceQueryConsultArgs_Req_DEFAULT *QueryConsultReq

func (p *ConsultServiceQueryConsultArgs) GetReq() (v *QueryConsultReq) {
	if !p.IsSetReq() {
		return ConsultServiceQueryConsultArgs_Req_DEFAULT
	}
	return p.Req
}

var fieldIDToName_ConsultServiceQueryConsultArgs = map[int16]string{
	1: "req",
}

func (p *ConsultServiceQueryConsultArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ConsultServiceQueryConsultArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ConsultServiceQueryConsultArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ConsultServiceQueryConsultArgs) ReadField1(iprot thrift.TProtocol) error {
	_field := NewQueryConsultReq()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Req = _field
	return nil
}

func (p *ConsultServiceQueryConsultArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("queryConsult_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ConsultServiceQueryConsultArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *ConsultServiceQueryConsultArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConsultServiceQueryConsultArgs(%+v)", *p)

}

type ConsultServiceQueryConsultResult struct {
	Success *QueryConsultResp `thrift:"success,0,optional"`
}

func NewConsultServiceQueryConsultResult() *ConsultServiceQueryConsultResult {
	return &ConsultServiceQueryConsultResult{}
}

func (p *ConsultServiceQueryConsultResult) InitDefault() {
}

var ConsultServiceQueryConsultResult_Success_DEFAULT *QueryConsultResp

func (p *ConsultServiceQueryConsultResult) GetSuccess() (v *QueryConsultResp) {
	if !p.IsSetSuccess() {
		return ConsultServiceQueryConsultResult_Success_DEFAULT
	}
	return p.Success
}

var fieldIDToName_ConsultServiceQueryConsultResult = map[int16]string{
	0: "success",
}

func (p *ConsultServiceQueryConsultResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ConsultServiceQueryConsultResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ConsultServiceQueryConsultResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ConsultServiceQueryConsultResult) ReadField0(iprot thrift.TProtocol) error {
	_field := NewQueryConsultResp()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Success = _field
	return nil
}

func (p *ConsultServiceQueryConsultResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("queryConsult_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ConsultServiceQueryConsultResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *ConsultServiceQueryConsultResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConsultServiceQueryConsultResult(%+v)", *p)

}
