// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	admin "buycar/biz/router/admin"
	module "buycar/biz/router/module"
	purchase "buycar/biz/router/purchase"
	score "buycar/biz/router/score"
	user "buycar/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user.Register(r)

	score.Register(r)

	purchase.Register(r)

	admin.Register(r)

	module.Register(r)
}
